### ISSUE TITLE
'jasmine is not defined' after adding karma-iframes

### ISSUE THREAD

**Issue by swachter** [sabberworm/karma-iframes#12]
After I added karma-iframes as documented I get the error: Uncaught ReferenceError: jasmine is not defined

**Comment by sabberworm** [comment]
Could you try to figure out what page the error appears on? Is it the page with the iframes on it or an individual iframed test page?

**Comment by swachter** [comment]
I am not sure how I can figure out the page the error appears on. Below is the error output. Maybe this contains a clue:

```
Chrome 79.0.3945 (Windows 7.0.0) ERROR
  Uncaught ReferenceError: jasmineRequire is not defined
  at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:23:1

  ReferenceError: jasmineRequire is not defined
      at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:23:1

Chrome 79.0.3945 (Windows 7.0.0) ERROR
  Uncaught ReferenceError: jasmineRequire is not defined
  at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:23:1

  ReferenceError: jasmineRequire is not defined
      at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:23:1
Chrome 79.0.3945 (Windows 7.0.0) ERROR
  Uncaught ReferenceError: jasmineRequire is not defined
  at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:6:3

  ReferenceError: jasmineRequire is not defined
      at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:6:3
      at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:81:3

Chrome 79.0.3945 (Windows 7.0.0) ERROR
  Uncaught ReferenceError: jasmineRequire is not defined
  at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:6:3

  ReferenceError: jasmineRequire is not defined
      at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:6:3
      at C:/project/app/node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:81:3
Chrome 79.0.3945 (Windows 7.0.0) ERROR
  Uncaught Error: Missing: jasmine.js
  at http://localhost:9876/_karma_webpack_/vendor.js:233437:13

  Error: Missing: jasmine.js
      at http://localhost:9876/_karma_webpack_/vendor.js:233437:19
      at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.js:233695:7)
      at http://localhost:9876/_karma_webpack_/vendor.js:233049:37
      at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.js:233053:2)
      at Object../node_modules/zone.js/dist/zone-testing.js (http://localhost:9876/_karma_webpack_/vendor.js:234616:30)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/main.js:85:30)
      at Object../src/test.ts (http://localhost:9876/_karma_webpack_/main.js:40845:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/main.js:85:30)
      at checkDeferredModules (http://localhost:9876/_karma_webpack_/main.js:46:23)
      at http://localhost:9876/_karma_webpack_/main.js:222:18

Chrome 79.0.3945 (Windows 7.0.0) ERROR
  Uncaught Error: Missing: jasmine.js
  at http://localhost:9876/_karma_webpack_/vendor.js:233437:13

  Error: Missing: jasmine.js
      at http://localhost:9876/_karma_webpack_/vendor.js:233437:19
      at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.js:233695:7)
      at http://localhost:9876/_karma_webpack_/vendor.js:233049:37
      at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.js:233053:2)
      at Object../node_modules/zone.js/dist/zone-testing.js (http://localhost:9876/_karma_webpack_/vendor.js:234616:30)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/main.js:85:30)
      at Object../src/test.ts (http://localhost:9876/_karma_webpack_/main.js:40845:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/main.js:85:30)
      at checkDeferredModules (http://localhost:9876/_karma_webpack_/main.js:46:23)
      at http://localhost:9876/_karma_webpack_/main.js:222:18
07 01 2020 14:33:50.789:WARN [Chrome 79.0.3945 (Windows 7.0.0)]: Disconnected (0 times), because no message in 30000 ms.
Chrome 79.0.3945 (Windows 7.0.0) ERROR
  Disconnected, because no message in 30000 ms.
```

This is the relevant configuration from `karma.conf.js`:

```
    frameworks: ['jasmine', '@angular-devkit/build-angular', 'iframes'],
    plugins: [
      require('karma-iframes'),
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
```
